"""Interactive first-run setup — `omb-setup`.

Writes a working config.yaml by asking plain questions, so a beginner never hand-edits YAML. Called
at the end of install.sh, and re-runnable any time (e.g. after adding modules). Stdlib + pyyaml only.
"""

from __future__ import annotations

import glob
import os
import sys

import yaml


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        ans = ""
    return ans or default


def _ask_int(prompt: str, default: int, lo: int = 1, hi: int = 64) -> int:
    while True:
        raw = _ask(prompt, str(default))
        try:
            n = int(raw)
            if lo <= n <= hi:
                return n
        except ValueError:
            pass
        print(f"  please enter a whole number between {lo} and {hi}")


def _ask_yn(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    ans = _ask(f"{prompt} ({d})", "").lower()
    if not ans:
        return default
    return ans.startswith("y")


def _detect_serial() -> str | None:
    """Return the first stable /dev/serial/by-id path, if any (preferred over /dev/ttyUSBn)."""
    found = sorted(glob.glob("/dev/serial/by-id/*"))
    return found[0] if found else None


def build_config() -> dict:
    print("\n=== open-murata-bms setup ===")
    print("Answer a few questions and I'll write your config. Press Enter to accept [defaults].\n")

    ess_name = _ask("Name for your battery system", "My Batteries")
    n = _ask_int("How many battery modules do you have", 4)

    print("\nHow is the Pi connected to the modules?")
    print("  1) USB-to-RS485 adapter plugged into the Pi   (most common)")
    print("  2) Network gateway (EW11 / Waveshare) over your LAN")
    conn = _ask("Choose 1 or 2", "1")

    if conn == "2":
        host = _ask("Gateway IP address", "192.168.1.100")
        port = _ask_int("Gateway TCP port", 502, hi=65535)
        transport = {"type": "rtu_over_tcp", "host": host, "port": port}
    else:
        detected = _detect_serial()
        if detected:
            print(f"\nFound a USB serial adapter: {detected}")
            use = _ask_yn("Use this adapter", True)
            portpath = detected if use else _ask("Serial device path", "/dev/ttyUSB0")
        else:
            print("\n(No USB serial adapter auto-detected — plug it in, or enter the path.)")
            portpath = _ask("Serial device path", "/dev/ttyUSB0")
        transport = {"type": "modbus_rtu",
                     "serial": {"port": portpath, "baudrate": 230400,
                                "bytesize": 8, "parity": "E", "stopbits": 1}}

    print("\nThe built-in web dashboard is ON by default — you'll open it in a browser after setup.")
    want_mqtt = _ask_yn("Also send data to Home Assistant? (needs an MQTT broker)", False)
    mqtt = {"enabled": False, "host": "127.0.0.1", "port": 1883,
            "username": None, "password": None,
            "base_topic": "open-murata-bms", "discovery_prefix": "homeassistant",
            "ha_discovery": True}
    if want_mqtt:
        mqtt["enabled"] = True
        mqtt["host"] = _ask("MQTT broker IP (use 127.0.0.1 if the broker runs on this Pi)", "127.0.0.1")
        mqtt["port"] = _ask_int("MQTT broker port", 1883, hi=65535)
        user = _ask("MQTT username (blank if none)", "")
        if user:
            mqtt["username"] = user
            mqtt["password"] = _ask("MQTT password", "")

    return {
        "ess": {"name": ess_name, "nominal_voltage": 48},
        "banks": [{
            "id": "bank1", "name": ess_name,
            "transport": transport,
            "timeout_ms": 25, "retries": 2,
            "slave_id_range": {"start": 1, "end": n},
        }],
        "limits": {"max_modules_per_bank": 32},
        "poll": {"interval_s": 0.5},
        "integration": {
            "web": {"enabled": True, "host": "0.0.0.0", "port": 8080},
            "mqtt": mqtt,
        },
        "safety": {"allow_writes": False, "allow_fault_clear": False},
        "log_level": "INFO",
    }


def main(argv: list[str] | None = None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    out = argv[0] if argv else "config.yaml"
    if os.path.exists(out):
        if not _ask_yn(f"\n{out} already exists — overwrite it", False):
            print("Keeping the existing config. Nothing changed.")
            return
    cfg = build_config()
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Generated by 'omb-setup'. Safe to edit by hand later.\n")
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
    print(f"\n✓ Wrote {out}")
    print("  Start (or restart) the service, then open the web dashboard:")
    print("    sudo systemctl restart omb    # if installed as a service")
    print("    →  http://<this-pi-ip>:8080\n")


if __name__ == "__main__":
    main()
